#!/bin/sh
sxhkd &
pgrep bspswallow || bspswallow &
~/.config/polybar/launch.sh &
setxkbmap -option caps:swapescape &
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144 --right-of HDMI-A-0 &
picom -f &
feh --bg-fill /home/eddie/pictures/background/mcis.jpg

bspc monitor DisplayPort-0 -d I III V VII IX 
bspc monitor HDMI-A-0 -d II IV VI VIII X 

bspc config border_width         2
bspc config window_gap           12

bspc config top_monocle_padding  -5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Pavucontrol state=floating
