#!/bin/sh
alias z="zathura"
alias vim="nvim"
alias vw="nvim ~/documents/notes/index.md"
alias cd1="cd .."
alias cd2="cd ../.."
alias cd3="cd ../../.."
alias cd4="cd ../../../.."
alias cd5="cd ../../../../.."
alias g="gcc -Wall -std=gnu99 -m32"
alias ytd-mp3="youtube-dl --extract-audio --audio-format mp3"
alias ytd-wav="youtube-dl --extract-audio --audio-format wav"
alias ytd-mp4="youtube-dl -f 'mp4'"

alias ls='ls --color=auto -h'
alias la="ls --color=auto -lah"
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinux-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias sdl="systemctl list-unit-files --state=enabled"

alias sve="source $ML_PATH/my_env/bin/activate"
alias nvd="cd $HOME/.config/nvim/lua"

alias sse="rsync -rvtzP $HOME/code/web/educhav/ root@educhav.xyz:/var/www/educhav"
alias ssg="rsync -rvtzP $HOME/code/web/greatamericanyouth/ root@educhav.xyz:/var/www/greatamericanyouth"
